m3db/m3x

- watch/source.go
- watch/source_test.go
- watch/watch.go
- watch/watch_test.go
Add a Initialized function to expose the status of the source, so the users can wait on it to be initialized if needed.
> Add WaitInit function to Source

- watch/watch.go
- watch/watch_test.go
Updating the watchable functionality for creating watches - giving an initial update to the created watch if the watchable has a value.
> Updating watchable functionality for new watches

- pool/bucketized.go
- pool/bytes.go
- pool/bytes_test.go
- pool/types.go
cc @robskillington @kobolog 
This PR makes bucketized pools (i.e., pools that allocate objects with different capacities) more generic so they can be used as the underlying pool types for other types.
> Make bucketized pools more generic

- pool/floats.go
- pool/floats_test.go
- pool/types.go
cc @kobolog @robskillington 
This PR adds a pool for float64 slices to be used from other repos, until the ability to generate type-specific native pools/heaps is in place.
> Add a pool for float64 slices

- pool/heap_test.go
- retry/options.go
- retry/retry.go
- retry/retry_test.go
- retry/types.go
cc @robskillington @kobolog @cw9 
This PR adds a parameter to the retrier options to bound the maximum backoff delay during retries.
> Add ability to bound the maximum backoff delay for retries

- net/server.go
- net/server_test.go
cc @robskillington @martin-mao @kobolog @cw9 
This PR adds `StartAcceptLoop` function to start server-side accept loops, returning connections channel and error channel for handlers to consume.
> Add utility function to start server-side accept loops

- instrument/options.go
cc @cw9 @kobolog 
This PR fixes a bug in `SetReportInterval` in that the current implementation is setting the interval on the wrong option object.
> Fix SetReportInterval() in instrument package

- .travis.yml
- checked/debug.go
- checked/debug_test.go
- checked/ref.go
- checked/ref_test.go
cc @kobolog @xichen2020 @cw9 @martin-mao
> Use program counters instead of stacks to track ref count usage

- checked/debug.go
- checked/ref.go
Before we were using a decref to ref zero as the traceback cycle end, however the true cycle end is when the owner finalizes the object (essentially calling it's destructor).  
This begins tracking it in the tracebacks and uses it as the cycle end instead of decref to ref zero.
cc @kobolog @xichen2020
> Track checked finalize events and use as the for marking traceback cycle end

- .ci/test-cover.sh
- checked/bytes.go
- checked/debug.go
- checked/debug_test.go
- checked/ref.go
- checked/ref_test.go
- checked/types.go
- pool/checked_object.go
- pool/heap.go
This PR adds support for leak detection tracking in checked objects by utilizing Go runtime finalizers. Essentially, each checked object can be marked for tracking by calling `Ref::TrackObject(v interface{})`, which will calculate the tracked allocation size and set a finalizer on the object that will determine whether it was garbage-collected while still having references. All detected leaks could then be queried with `DumpLeaks()` function.
> Add leak detection support.

- pool/object.go
- pool/object_test.go
- pool/options.go
- pool/types.go
> Add use before initialization checks to the ObjectPool

- errors/errors.go
- errors/errors_test.go
cc @robskillington @cw9 
Add "[]" around the error string for `Errors` type since it's a slice of errors
> Add square brackets around error string for Errors

- unsafe/string.go
- unsafe/string_benchmark_test.go
- unsafe/string_test.go
cc @kobolog @robskillington @jeromefroe @cw9 @prateek 
This PR adds the unsafe package to perform zero-allocation conversion from string to byte slices, which will significantly reduce GC when we need to encode string ids as byte slices.
> Add unsafe package to perform zero-allocation conversion from string to byte slice

- unsafe/string.go
- unsafe/string_benchmark_test.go
- unsafe/string_test.go
cc @jeromefroe @kobolog @robskillington 
This PR passes a callback function to process byte array backing the string without memory allocation. Because we are guaranteed that the string is in scope when the callback function is called, as long as the callback function doesn't mutate the byte slice and doesn't hold reference to the byte slice when it returns, it should be safe.
> Pass a callback function to process byte array backing the string

- log/logger.go
- log/logger_test.go
There was a panic when calling NullLogger.WithFields() because the
fields was nill
@xichen2020 @robskillington @prateek
> fix panic in NullLogger

- glide.lock
- glide.yaml
- instrument/config.go
- instrument/options.go
- pool/config.go
- pool/config_test.go
- pool/options.go
- retry/config.go
- retry/config_test.go
cc @jeromefroe @martin-mao @cw9  @robskillington 
This PR adds metrics configurations to `instrument/` for reuse across repos.
> Add instrumentation and retry configurations

- pool/object.go
cc @robskillington @cw9 @jeromefroe @prateek 
This PR sets the gauges after the object pool is initialized.
> Set gauges after pool is initialized

- clock/options.go
- clock/types.go
cc @cw9 @jeromefroe @robskillington @prateek 
This PR adds max positive clock skew and max negative clock skew as part of the clock options.
> Add max positive skew and max negative skew to clock options

- time/unit.go
- time/unit_test.go
cc @robskillington @cw9 @jeromefroe @prateek 
This PR adds a utility function to determine the maximum unit for a duration. This is needed when user provides a policy without specifying the resolution precision unit (e.g., "10s:1d"), in which case we use this function to determine what precision unit we should use (in this case 1s).
> Add a utility function to determine the maximum unit for a duration

- server/server.go
- server/server_test.go
@xichen2020 @cw9 
This PR adds a `Serve(l net.Listener)` method to the `Server` interface so that we can explicitly pass a listener to a `Server`. This will be helpful in testing when we don't know in advance what port we want to listen on.
> [servers] Add Serve method to server interface

- net/server.go
- net/server_test.go
- server/options.go
- server/server.go
- server/server_test.go
Add this API as per discussion, although I feel we should just change ListenAndServe() and Serve() to do the Forever thing under the hood rather than adding this new API, because the user of the server interface has no way of knowing if the server has gone out of retries.
@xichen2020 @robskillington @jeromefroe @prateek
> Add ListenAndServeForever to m3x server

- server/options.go
- server/server.go
cc @cw9 
This PR adds support to optionally set keepAlives for TCP connections.
> Optionally support keepalives for tcp connections

- server/options.go
- server/server.go
cc @cw9 
This enables setting keepAlive period for TCP connections in the server.
> Enable setting keepAlive period for tcp connections

- time/range.go
- time/range_test.go
cc @cw9 @robskillington 
This PR adds `Equal()` to `xtime.Range` to properly compare two time ranges.
> Add Equal() to xtime.Range

- instrument/build.go
Turns out ldflags can only set string vars. Updating our implementation for that.
/cc @jeromefroe
> Fix LogBuildInfoAtStartup

- time/range.go
- time/range_test.go
- time/unit.go
- time/unit_test.go
This PR adds a `Duration` method to the `Range` struct in the `time` package which returns the duration of the range a `Count` method to `Unit` which returns the number of units contained within a duration.
cc @xichen2020
> [time] Add a Duration method to Range and a Count method to Unit

- errors/errors.go
- errors/errors_test.go
This PR adds two functions, `Wrap` and `Wrapf`, that allow one to wrap an error with additional context while still preserving the underlying type of the error. These functions address the problem that one cannot use `fmt.Errorf` to wrap errors because that loses the type information of the error which is being wrapped. One can accomplish the same thing currently with `NewRenamedError` and `Wrap` and `Wrapf` aim to make such tasks easier to perform.
> [errors] Add functions to Wrap errors and preserve type

- glide.lock
- glide.yaml
- id/hash.go
- id/hash_bench_test.go
- id/hash_test.go
cc @jeromefroe @cw9 @prateek 
This PR adds murmur3 as a more efficient and equally good collision-wise alternative to generate 128-bit hashes of ids.
```
BenchmarkMD5ShortID-8               	10000000	       151 ns/op
BenchmarkMD5MediumID-8              	 3000000	       421 ns/op
BenchmarkMD5LongID-8                	  200000	     11567 ns/op
BenchmarkMurmur3Hash128ShortID-8    	100000000	        24.4 ns/op
BenchmarkMurmur3Hash128MediumID-8   	30000000	        50.8 ns/op
BenchmarkMurmur3Hash128LongID-8     	 1000000	      1232 ns/op
```
> Add mumur3 128-bit as a more efficient alternative for hashing ids

- config/hostid/hostid.go
- config/hostid/hostid_test.go
This is a port as it might be useful for other projects that resolve the host ID in a configuration driven manner.
As you suggested @prateek.
> Add hostid config package for resolving a host ID

- log/logger.go
cc @cw9 @robskillington @prateek @jeromefroe 
This PR makes null logger a pointer type.
> Remove field slice in nulllogger to make it comparable

- glide.lock
- glide.yaml
- instrument/options.go
- instrument/types.go
This PR adds a `zap` logger to the `instrument.Options` interface. `zap` offers a performant logger which is actively maintained. In addition, it provides a number of other features include log sampling and the ability to dynamically change the log level. By adding `zap` as a new method on the `Options` interface we can migrate current packages piecemeal as the need arises.
> [instrument] Add zap logger to options interface

- instrument/extended.go
Add a metric for `GCCPUFraction`, which tracks the percentage of total available CPU time that was spent on garbage collection.
cc @xichen2020 @prateek
> [instrument] Add metric for GC CPU Fraction

- time/range_iter.go
- time/ranges.go
- time/ranges_test.go
We've seen panics due to the nil-ability of Ranges as it is a pointer type.  It would be wise to convert all the time based structures from interfaces to structs to align on consistency.  
The structure is already immutable so the API does not need to change to convert this to a struct.
> Make Ranges struct based to avoid nil-ability of Ranges (it is immutable too)

- instrument/build.go
- instrument/build_test.go
Turns out LDFlags need to be strings. Porting the unix nanos number to a string
> Fix age reporter

- pool/object.go
- pool/object_test.go
On a frequently accessed pool, we actually spend a lot of time on calling time.Now(), this change should save 600-700ns per operation.
@xichen2020 @robskillington @prateek @jeromefroe
> Improve object pool performance

- config/config.go
- config/config_test.go
- config/example_test.go
- glide.lock
- glide.yaml
The current unmarshalling is susceptible to setting keys that are missing in the config resulting in unexpected default values when the key used is wrong.
This change makes config loading use the new `yaml.UnmarshalStrict` method now available in `gopkg.in/yaml.v2`.
> Use strict YAML unmarshal when loading config

- generated-source-files.mk
- Migrate to `-ast` generator
- Avoid creating `type struct{} interface{}` 
Verified this doesn't break any of the maps gen'd in m3db
> Fix genny generation of map with struct{} value type

- retry/retry.go
- retry/types.go
This pr exposes the function to return the backoff nanoseconds for a given retry, so I can reuse the math in a case where I don't actually need the attempt().
This pr changes the underlying math slightly.
@robskillington @xichen2020 @prateek @jeromefroe
> Expose the math for calculating backoff time

- retry/retry.go
It makes more sense to pass in `1st` retry than `0th` retry
> Improve BackoffNanos interface

- retry/config.go
- retry/retry.go
- retry/retry_test.go
This pr fixes a bug in the backoff calculation which could generate negative result after many retries: for example with the following input:
retry: 50
jitter: true/false
backoffFactor: 2.0
initialBackoff: 10ms
maxBackoff: 50ms
The reason is that 10^7 * math.Pow(2.0, 50) would overflow when being converted to int64, the original implementation is much less prone to negative backoff result but still possible, luckily time.Sleep is safe(does not panic) on zero or negative duration. 
This pr fixes the issue but could probably use a better way to detect whether the negativity is coming from the math overflow to be more exact.
@xichen2020 @prateek @robskillington
> Avoid negative result in retry backoff

- instrument/build.go
Add a flag for the version of the build. Will be beneficial with releases so that users can see the explicit version they are running instead of just the SHA.
> [build] Add flag for version of build

- ident/identifier_pool.go
We decided this change was too dangerous as we found a location in M3DB where it would have caused problems
> Revert "Optimize ID pool to not clone if ID is NoFinalize (#192)"

- glide.lock
- glide.yaml
- sync/pooled_worker_pool.go
Standard lib RNG is a 5KiB allocation whereas the PCG RNG is a two word allocation
> Use PCG RNG in PooledWorkerPool to reduce allocations

- errors/errors.go
- errors/errors_test.go
- errors/example_test.go
Allows only the last error to be extracted; useful for cases where any amount of errors leads to a failure, but individual messages are less important. 
Part of a resolution for: https://github.com/m3db/m3/issues/973
> Add last error method on MultiError struct

- config/hostid/hostid.go
- config/hostid/hostid_test.go
Under some orchestration systems, such as Kubernetes, we may need to
read host identity from a file on disk that is dynamically populated
with instance metadata. Additionally, this metadata may sometimes be
populated by an external actor and may not be available at startup, so
we provide an optional timeout to wait for it.
As a concrete example, on Kubernetes this supports reading host ID from
pod metadata that is injected using [downward API
volumes](https://git.io/fp4hL). The host ID may not be immediately
populated, but the user can provide a timeout that the instance will
wait for it before failing to start. An example of a pod metadata file
in Kubernetes is:
```
root@matt-test-656988ff69-gk49b:/# cat /etc/podinfo/id
test-id
```
> [hostid] support reading ID from a file

- glide.lock
- glide.yaml
It was essentially locked to v3.3.6 - while m3db requests ^3.3.6, make it possible to include in projects with pin set to ^3.3.7.
> Relax pin on Tally and update dependencies
