m3db/m3x

errors/errors.go
errors/errors_test.go

R: @xichen2020 @robskillington

pull latest errors from m3db

---

time/unit.go
time/unit_test.go

R: @robskillington @xichen2020

Add Unit.String() and use tables for lookup

---

errors/errors.go
retry/options.go
retry/retry.go
retry/retry_test.go
retry/types.go

cc @xichen2020 @mmihic @martin-mao @cw9

Add xretry package with Retrier

---

watch/source.go
watch/source_test.go
watch/watch.go
watch/watch_test.go

add header

---

glide.lock
glide.yaml

Lock glide version

---

watch/source.go
watch/source_test.go

Add Get() to Source

---

sync/worker_pool.go
sync/worker_pool_test.go

R: @robskillington @xichen2020

add worker pool to m3x

---

errors/errors.go
errors/errors_test.go

R: @robskillington @xichen2020

add Empty method to MultiError

---

.gitignore
debug/mutex.go
debug/mutex_test.go

cc @xichen2020 @martin-mao @cw9 @mmihic

Add debug RWMutex

---

.travis.yml
errors/errors.go

cc @xichen2020 @cw9 @martin-mao

Add the ability for others to add their own contained errors

---

errors/errors.go
errors/errors_test.go

Used for refactoring in m3db/m3db.

add NumErrors to MultiError

---

instrument/methods.go
instrument/options.go
instrument/types.go
pool/bytes.go
pool/bytes_test.go
pool/heap.go
pool/heap_test.go
pool/mmap.go
pool/mmap_darwin.go
pool/mmap_linux.go
pool/native.go
pool/native_test.go
pool/object.go
pool/object_test.go
pool/options.go
pool/types.go

This PR moves `pool` and `instrument` common packages from M3DB to M3X since they are going to be reused in other projects.

Move some common stuff over from M3DB.

---

time/unit.go
time/unit_test.go

Add time unit minute

---

pool/bytes.go
pool/bytes_test.go
pool/heap.go
pool/heap_test.go

Return nil when requesting bytes of zero capacity

---

clock/options.go
clock/types.go

Move clock options to m3x

---

instrument/types.go

cc @robskillington 
This PR adds a reporter interface to report runtime information (e.g., metrics)

Add reporter interface

---

hash/jump/doc.go
hash/jump/jump.go
hash/jump/jump_test.go

Add implementation of jump consistent hash algorithim

---

id/hash.go
id/hash_test.go

cc @robskillington @kobolog 
This PR adds the id package so we can use the same id hashing mechanism across repos.

Add id package to provide consistent id hashing across repos

---

time/unit.go
time/unit_test.go

@xichen2020 This PR exposes a function to get `time.Duration` from a `Unit`.

Expose function to get time.Duration from Unit

---

config/config.go
config/config_test.go
glide.lock
glide.yaml

@xichen2020 @prateek @robskillington

Add config parser

---

config/config.go
config/config_test.go
config/pool.go
pool/config.go

cc @cw9 @prateek @martin-mao 
This PR adds configs for various types of pools.

Add various pooling configs

---

pool/config.go

cc @cw9 @jeromefroe 
This PR renames config to configuration for consistency.

Rename config to configuration for consistency

---

pprof/pprof.go
pprof/pprof_test.go

cc @jeromefroe @cw9 @prateek @martin-mao 
This PR adds the pprof handler for custom http mux.

Add pprof handler for custom http mux

---

retry/config.go
retry/config_test.go
retry/options.go
retry/retry.go
retry/retry_test.go
retry/types.go

cc @cw9 @jeromefroe @martin-mao @prateek 
This PR adds an option to allow infinite retries.

Add an option to allow infinite retries

---

glide.lock
glide.yaml
instrument/config.go
instrument/runtime.go

cc @robskillington @cw9 @jeromefroe @prateek 
This PR adds ability to report runtime metrics.

Report extended metrics

---

tcp/tcp.go

Add TCP KeepAliveListener

---

clock/config.go

This PR adds configuration for clock options.

Add configuration for clock options

---

server/options.go
server/server.go
server/server_test.go

So it can be reused by aggregator, ingester etc.
@xichen2020

Move server from m3aggregator to m3x

---

server/server.go
server/server_test.go

Add Close function to server handler interface

---

retry/config.go
retry/config_test.go

Add NewOptions() to retry config

---

retry/config.go
server/server.go

Reuse Serve() in m3x server

---

checked/bytes.go
checked/debug.go

Avoid interface alloc when leak detection disabled

---

time/range.go
time/range_test.go

- Utility method to squeeze a range within another
/cc @martin-mao @xichen2020

Add Range.Intersect()

---

time/duration.go
time/duration_test.go
time/unit.go
time/unit_test.go

cc @cw9 @dgromov @jeromefroe 
This PR adds more time units (hour, day, week, month, and year) and added `ToExtendedString` to support more user-friendly string representation of durations. For example, instead of using `24h0m0s` as the string representation of a duration with value `24 * time.Hour`, it'll simply be `1d`.

Support more time units and more user-friendly string for durations

---

watch/source_test.go

Fix TestSource

---

instrument/methods.go

cc @cw9 @robskillington 
This PR exports the constructors for creating sampled timers.

Export constructors for creating sampled timers

---

time/unit.go
time/unit_test.go

Add year unit

---

ident/iterator.go
ident/iterator_test.go
ident/tag_iterator.go
ident/tag_iterator_test.go
ident/types.go

Add `ident` utility methods

---

context/context.go
context/options.go
context/pool.go
context/types.go

Add context pool options

---

ident/identifier_pool.go
ident/identifier_pool_test.go
ident/identifier_test.go
ident/iterator.go
ident/iterator_test.go
ident/tag_iterator.go
ident/tag_iterator_test.go
ident/types.go

Add utility methods to ident.Pool

---

instrument/build.go
instrument/build_test.go

/cc @robskillington @jeromefroe

Add age reporting in instrument.BuildReporter

---

.metalinter.json
Makefile
generated-source-files.mk

- no more docker as a ci build dep

Update genny generation to use forked gorename

---

context/finalizers_arraypool_gen.go
generics/arraypool/pool.go

- Prefer allocating and retaining instead of allocating and throwing away the slice

Fix arraypool grow

---

generated-source-files.mk

- Ability to disable generation of key/value type stubs during generation
- Ability to override the stubbed key/value type during generation

Allow overrides on key/value type

---

glide.lock
glide.yaml
retry/retry.go
retry/retry_test.go

Prevent panic in rand.Int63n

---

sync/options.go
sync/pooled_worker_pool.go
sync/pooled_worker_pool_test.go
sync/types.go
sync/worker_pool.go

Tested on one of our production clusters and it reduced end-to-end latency significantly. In addition, the amount of time spent in runtime.morestack in the CPU profiles also decreased drastically.

Implement pooled worker pool

---

instrument/invariant.go
instrument/invariant_test.go

Add support for panicing on invariant violations in instrument package

---

glide.lock
glide.yaml
instrument/options.go
instrument/tracing.go
instrument/tracing_test.go
instrument/types.go

This is a small preparatory diff to add support for tracing to m3query. I figured I might as well do the config here, since that's where we have metrics + logging. Let me know if you'd rather have this code elsewhere!

Add tracing config

---

context/context.go
context/context_test.go

Add Go's stdlib context to m3x's context

Add goCtx to xCtx

---

context/context_test.go
context/types.go

Forgot to add to the interface

Add go std ctx functions to interface
